---
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

parserOptions:
  ecmaVersion: 8
  sourceType: module

globals:
  pageState: writable
  pageContent: writable
  realPages: writable
  module: writable


rules: 
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_

env:
  browser: true
  es6: true
