---
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - sort-imports-es6-autofix

parserOptions:
  ecmaVersion: 9
  sourceType: module
  experimentalObjectRestSpread: true

globals:
  pageContent: writable
  module: writable


rules: 
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
  sort-imports-es6-autofix/sort-imports-es6: 
    - 2

env:
  browser: true
  es6: true
